### ISSUE TITLE
/root/.aws-credential-helper.py: Permission denied

### ISSUE THREAD

**Issue by pnipinto** [aws-samples/sagemaker-studio-lifecycle-config-examples#27]
Hi, 

I've created the LCC for SM Studio on starting the Jupyter Server however I am getting this error when I try to push changes to my repo. Checked the git config and there don't seem to be any issues there. Any suggestions?

![Screen Shot 2022-12-20 at 4 50 07 pm](https://user-images.githubusercontent.com/118334113/208624129-665385b4-578d-4e9d-b007-3907df974173.png)

**Comment by rvben** [comment]
Hi @pnipinto,

An error like this typically is a result of directly calling a file that is not executable.
You can make /root/.aws-credential-helper.py executable by running:

```bash
sudo chmod +x /root/.aws-credential-helper.py
```

Does that resolve your issue?

**Comment by pnipinto** [comment]
Yes thank you!
