### ISSUE TITLE
add-lcc-script.sh hard-codes us-east-2 region

### ISSUE THREAD

**Issue by athewsey** [aws-samples/sagemaker-studio-lifecycle-config-examples#32]
The `add-lcc-script.sh` example script parameterizes the script name, filename, script type etc, but [hard-codes the us-east-2 region](https://github.com/aws-samples/sagemaker-studio-lifecycle-config-examples/blob/a9ef779348d51f4b04b40c111dc24d419077cf9b/add-lcc-script.sh#L13) - which is confusing for users (we spent some time not figuring out why our scripts were appearing in console!)

Please make the region another config variable at the top of the script! 😄

**Comment by durgasury** [comment]
Closing this issue after merging PR #33
