### ISSUE TITLE
[Bug] install-lsp-features fetches unsupported version of bash-language-server

### ISSUE THREAD

**Issue by athewsey** [aws-samples/sagemaker-studio-lifecycle-config-examples#34]
NPM package [bash-language-server](https://github.com/bash-lsp/bash-language-server) provides IDE-like autocomplete/hinting for Jupyter in the `install-lsp-features` sample LCC (used [here](https://github.com/aws-samples/sagemaker-studio-lifecycle-config-examples/blob/a9ef779348d51f4b04b40c111dc24d419077cf9b/scripts/install-lsp-features/on-jupyter-server-start.sh#L34)).

However, this week they released major version `5.0.0` which [drops support for NodeJS v14](https://github.com/bash-lsp/bash-language-server/blob/3fb622eaf1ef93af07a896947610638ca72d7b4e/server/package.json#L17)... And currently, SageMaker Studio JupyterServer seems to use NodeJS v14 so the sample now fails to run.

Suggest pinning this install as e.g. `bash-language-server@"<5.0.0"` until Studio JupyterServer environment gets updated?

**Comment by durgasury** [comment]
PR #35 merged
