### ISSUE TITLE
Auto-shutdown samples reference an outdated tarball

### ISSUE THREAD

**Issue by athewsey** [aws-samples/sagemaker-studio-lifecycle-config-examples#4]
Both [install-autoshutdown-extension](https://github.com/aws-samples/sagemaker-studio-lifecycle-config-examples/blob/25c9d432c7e1a03cbd8ee17874c358cb470ae62a/scripts/install-autoshutdown-extension/on-jupyter-server-start.sh) and [install-autoshutdown-server-extension](https://github.com/aws-samples/sagemaker-studio-lifecycle-config-examples/blob/25c9d432c7e1a03cbd8ee17874c358cb470ae62a/scripts/install-autoshutdown-server-extension/on-jupyter-server-start.sh) currently seem to reference `sagemaker_studio_autoshutdown-0.1.1.tar.gz`, but according to https://github.com/aws-samples/sagemaker-studio-auto-shutdown-extension the latest available seems to be `0.1.2`

**Comment by durgasury** [comment]
Scripts are updated to use the latest tarball.
