### ISSUE TITLE
Getting error "nohup: failed to run command 'supervisorctl': No such file or directory"

### ISSUE THREAD

**Issue by mailjunze** [aws-samples/sagemaker-studio-lifecycle-config-examples#8]
nohup: failed to run command 'supervisorctl': No such file or directory while deploying install-autoshutdown-server-extension

Also, this failed "cd /home/sagemaker-user" as the script was running in root directory. No such sagemaker user !

Using the default data science image

https://github.com/aws-samples/sagemaker-studio-lifecycle-config-examples/blob/main/scripts/install-autoshutdown-server-extension/on-jupyter-server-start.sh

**Comment by ZhangHan** [comment]
This script is used for restarting JupyterServer as mentioned in the script name and comment. Kernel Gateway apps (data science image for example) are not launched through supervisorctl which is why you got that error.

**Comment by mailjunze** [comment]
Thanks for your input. How can we restart Kernel Gateway apps ?

**Comment by mailjunze** [comment]
sed -i -e 's/\r$//' scriptname.sh

**Comment by durgasury** [comment]
You can shut down and restart the kernel gateway apps as specified in the [documentation](https://docs.aws.amazon.com/sagemaker/latest/dg/studio-tasks-update-apps.html).
